[build]
publish = "dist"
command = "pnpm run build"
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
[dev]
command = "pnpm run build" # Command to start your dev server
targetPort = 3000          # # The port for your application server, framework or site generator
port = 8888                # The port that the netlify dev will be accessible on
publish = "dist"           # If you use a _redirect file, provide the path to your static content folder
[[redirects]]
from = "/meet"
to = "https://calendly.com/amp-42/discovery"
status = 301
force = false
query = { path = ":path" }
conditions = { Language = ["en"], Country = ["US"] }
